version: "3.1"

services:
  main:
    build: "."
    ports:
      - "8080:8080"
  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data/"
  redis:
    image: "redis"
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
