version: "3.1"

services:
  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "amble"
      POSTGRES_DB: "amble"
      POSTGRES_PASSWORD: "amble"
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data/"
  redis:
    image: "redis"
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
