use chrono::{DateTime, Utc};
use juniper::graphql_object;
use sqlx::FromRow;
use uuid::Uuid;

/// Represents a user in the "users" table.
#[derive(Debug, Clone, FromRow)]
pub struct User {
    /// The unique ID of the user.
    pub id: Uuid,
    /// Auto-generated timestamp specifying when this user was created.
    pub created_at: DateTime<Utc>,
    /// Auto-generated timestamp specifying when this user was last updated.
    pub updated_at: DateTime<Utc>,
    /// The user's username.
    pub username: String,
    /// The user's email address.
    pub email: String,
    /// Timestamp specifying when the user's email address was last verified. This will be none if
    /// the email address hasn't been verified yet.
    pub email_verified_at: Option<DateTime<Utc>>,
    /// A hash of the user's password, generated by the "bcrypt" algorithm. We can use this to
    /// verify a password is correct without actually storing the plain-text password in the
    /// database.
    pub password_hash: String,
}

/// Defines the fields exposed by GraphQL.
#[graphql_object]
impl User {
    pub fn id(&self) -> &Uuid {
        &self.id
    }

    pub fn created_at(&self) -> &DateTime<Utc> {
        &self.created_at
    }

    pub fn updated_at(&self) -> &DateTime<Utc> {
        &self.updated_at
    }

    pub fn username(&self) -> &str {
        &self.username
    }

    pub fn email(&self) -> &str {
        &self.email
    }

    pub fn email_verified_at(&self) -> &Option<DateTime<Utc>> {
        &self.email_verified_at
    }
}
